name: plex

services:

  server:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ./config:/config
      - ${PLEX_MEDIA_DIR}:/data
    tmpfs:
      - /transcode
